### ISSUE TITLE
执行pnpm build 报错

### ISSUE THREAD

**Issue by Create-Peace** [element-plus/element-plus-icons#41]
pnpm : 7.0.0-rc.2,
node: v16.14.2,
执行 pnpm build, 
```
> @element-plus/icons-vue@1.1.4 build D:\workspace\element-plus-icons\packages\vue
> pnpm run build:generate && pnpm run build:build && pnpm run build:types

> esno build/generate.ts

i generating vue components                                                                                                          13:15:11  
d:\workspace\element-plus-icons\packages\vue\build\generate.ts:14
  const { rootPath } = await getPackageInfo('@element-plus/icons-svg')
          ^

TypeError: Cannot destructure property 'rootPath' of '(intermediate value)' as it is undefined.
    at null.getSvgFiles (d:\workspace\element-plus-icons\packages\vue\build\generate.ts:14:11)
    at null.<anonymous> (d:\workspace\element-plus-icons\packages\vue\build\generate.ts:68:17)
```

**Comment by sxzz** [comment]
fixed in 08ad969d38504589496d4e657ce5dc2f9a1c23eb
